import type { Metadata } from "next";
import {  Bodoni_Moda, Passions_Conflict } from "next/font/google";
import "./globals.css";

const bodoniModa = Bodoni_Moda({
  display: 'swap',
  subsets: ["latin"],
  variable: '--font-bodoni-moda'
});

export const passions_conf = Passions_Conflict({
  subsets: ['latin'],
  display: 'swap',
  weight: '400', 
  variable: '--font-passions-conflict'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bodoniModa.variable}  ${passions_conf.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
